### PR TITLE
Use publish date for article notifications

### LINKED ISSUE #3300: Notifications showing incorrect "Posted X days ago"
**Describe the bug**
On the notification page, some posts are showing "Posted {x} days ago" when they should show a few minutes ago (shows correctly on Latest listings).

**To Reproduce**

1. Go to Notifications
2. Scroll through recent notifications looking for an item that is part of a series (the 2 I found were both series. Might be coincidence)
3. Note the "days ago" timing
4. Navigate to the post to see when the post was published. 

We found this in this twitter exchange: https://twitter.com/PichuPlayer/status/1143504346279272450

**Expected behavior**
It looks like the draft date is being used in place of the publish date for the notification calculations.

**Screenshots**
Notification - 
Laurie's post notification indicating it was posted 4 days ago

Latest Feed -
Laurie's post in the Latest feed indicating it was posted less than 1 hour ago.

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser: Firefox
- Version: 68.0b12 (64-bit)

### PR DESCRIPTION
**Pull request by Zhao-Andy**
## What type of PR is this? (check all applicable)
- [x] Bug Fix

## Description
This fixes an issue where an article notification was showing the `created_at` date instead of the `published_at` date. I also added some minor adjustments to handle it the way we usually handle notification data.

Resolves #3300

### CODE REVIEW

File: spec/requests/notifications_spec.rb [hunk 1]
```diff
@@ -1,4 +1,5 @@
 require "rails_helper"
+include ActionView::Helpers::DateHelper
```
Comment (Zhao-Andy) [inline spec/requests/notifications_spec.rb]: This is probably fine and won't slow things _that_ much, I think.
