### PR TITLE
Fix Github repo pin and and unpin

### LINKED ISSUE #6571: Cannot remove pinned GitHub repositories from profile.
**Describe the bug**

Clicking in the Remove button in the "Pin a few of your GitHub repos to your profile" section does not remove the repository from your Pinned repositories.

Observing the network activity we can see that a POST request is sent to https://dev.to/github_repos/update_or_create with `featured` set to `false`

```
------WebKitFormBoundaryJSPfqsd1l1CtbXst
Content-Disposition: form-data; name="github_repo"

{"github_id_code":92339815,"featured":false}
------WebKitFormBoundaryJSPfqsd1l1CtbXst--
```

but the response returns

```json
{"featured":true}
```

**To Reproduce**
1. Go to https://dev.to/settings/integrations
2. Try to remove a pinned repository.
4. It won't work

dev-to--bug

### PR DESCRIPTION
**Pull request by rhymes**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Removing a Github repo from pinning in the user's settings is currently broken. This PR fixes it.

Closes #6571

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

pingithub

## Added tests?

- [x] yes
- [ ] no, because they aren't needed
- [ ] no, because I need help

### CODE REVIEW

File: spec/requests/github_repos_spec.rb [hunk 1]
```diff
@@ -90,20 +98,49 @@
...
+      previous_date = user.github_repos_updated_at
+
+      Timecop.travel(5.minutes.from_now) do
+        params = { github_repo: github_repo.to_json }
+        post update_or_create_github_repos_path(params), headers: headers
+        expect(user.reload.github_repos_updated_at > previous_date).to be(true)
+      end
+    end
+
+    it "set true for a featured repo" do
```
Comment (vaidehijoshi) [inline spec/requests/github_repos_spec.rb]:
```suggestion
    it "allows the repo to be featured" do
```

File: spec/requests/github_repos_spec.rb [hunk 2]
```diff
@@ -90,20 +98,49 @@
...
+      github_repo[:featured] = true
+      params = { github_repo: github_repo.to_json }
+      post update_or_create_github_repos_path(params), headers: headers
+
+      expect(response.parsed_body["featured"]).to be(true)
+    end
+
+    it "returns false for a repo removed from featured" do
```
Comment (vaidehijoshi) [inline spec/requests/github_repos_spec.rb]:
```suggestion
    it "allows the repo to be unfeatured" do
```
