### PR TITLE
Return a Unauthorized Error from API when Current User is Not Found

### LINKED ISSUE #6119: Return a Unauthorized Error from API when Current User is Not Found
There are a couple of endpoints in our API where we require a current_user to be present but we are not ensuring that it exists during our authentication. The two endpoints we have seen errors from because of this are below:
Honeybadgers and Errors:
https://app.honeybadger.io/fault/66984/029a751b03584e85380d5f6b69de050f
```
NoMethodError: undefined method `follows_by_type' for nil:NilClass
followings_controller.rb  8 users(...)
[PROJECT_ROOT]/app/controllers/api/v0/followings_controller.rb:8:in `users'
 6 
 7       def users
 8         relation = current_user.follows_by_type("User").
 9           select(ATTRIBUTES_FOR_SERIALIZATION).
10           order(created_at: :desc)
```
https://app.honeybadger.io/fault/66984/ea66d2941c66d56887febf955a5e16e3
```
NoMethodError: undefined method `id' for nil:NilClass
github_repos_controller.rb  43 create_octokit_client(...)
[PROJECT_ROOT]/app/controllers/api/v0/github_repos_controller.rb:43:in `create_octokit_client'
41 
42       def create_octokit_client
43         current_user_token = Identity.find_by(provider: "github", user_id: current_user.id).token
44         Octokit::Client.new(access_token: current_user_token)
```

**Desired Behavior** 
In these situations, we should be requiring that a `current_user` be present before attempting to perform the action. If current_user is not present we should return a 401, unauthorized status which we have a helper method for in the ApiController
```ruby
  def error_unauthorized
    render json: { error: "unauthorized", status: 401 }, status: :unauthorized
  end
```

### PR DESCRIPTION
**Pull request by citizen428**
## What type of PR is this? (check all applicable)

- [X] Bug Fix

## Description

This PR fixed incorrect usage of `current_user` instead of `@user` in several API controllers.

## Related Tickets & Documents

Closes #6119

## Added tests?

- [X] yes

## Added to documentation?

- [X] no documentation needed

### CODE REVIEW

**Comment by citizen428** [comment]
@mstruve As @rhymes pointed out in the ticket description, `Api::V0::FollowingsController` already has the necessary `before_action` and the spec confirms it's working. Before I spend too much time debugging this, how often does this error occur for followings?

**Comment by mstruve** [comment]
Question, when you authorize by `api_key`, does that ALWAYS set `current_user`? Bc I noticed in most places in the API we are using `@user` instead of `current_user` and wondered if maybe we don't expect current_user to be set in some cases. This is not super frequent but enough that its making noise in our error reporting so we should fix it.

**Comment by rhymes** [comment]
+1 on finding the actual reason why this is happening :)

**Comment by citizen428** [comment]
Yup, definitely seems worthwhile getting to the bottom of this, thanks for the context @mstruve

**Comment by maestromac** [comment]
@mstruve  `current_user` is nil when you are authorized by api_key. `authenticate_with_api_key_or_current_user!` is defaulting to using/setting `@user` but that's clearly not the case throughout v0's controllers.

**Comment by mstruve** [comment]
AH, that is what I assumed! Thanks @maestromac for digging into that further. Definitely ping me when ready for a PR review, happy to help get this straightened out.

**Comment by citizen428** [comment]
@mac Thanks for the context, that helped a lot! Having to remember to use `@user` and not `current_user` in API controllers will potentially lead to more bugs down the road, we should probably find a better fix for this at one point in time.

@rhymes I wasn't sure about `Api::V0::ChatChannelsController`, it has no `before_action` for authentication, but relies on `current_user` and does a `sign_in user` in the spec. I didn't include the changes for that yet, but I have them locally, please let me know if I should include them here.

File: app/controllers/api/v0/follows_controller.rb [hunk 1]
```diff
@@ -6,7 +6,7 @@ class FollowsController < ApiController
       def create
         user_ids = params[:users].map { |h| h["id"] }
         user_ids.each do |user_id|
-          Users::FollowWorker.perform_async(current_user.id, user_id, "User")
```
Comment (citizen428) [inline app/controllers/api/v0/follows_controller.rb]: Added a spec for this that failed when using `current_user` and now passes.

File: spec/requests/api/v0/followings_spec.rb [hunk 2]
```diff
@@ -20,6 +20,19 @@
       end
     end
 
+    # See: https://github.com/thepracticaldev/dev.to/issues/6119
+    context "when user is authorized with an API key" do
+      let_it_be(:api_secret) { create(:api_secret, user: user) }
+
+      %w[users tags organizations podcasts].each do |type|
```
Comment (citizen428) [inline spec/requests/api/v0/followings_spec.rb]: All the methods used `current_user`, so I added a spec for each case. Garbage objects are IMHO less of a concern so I left the array inline, which also helps with Rubocop not complaining about `stub_const` (it can't now that we're not trying to do that but instead define a constant for use inside the spec, due to the way constant lookup works in Ruby).

File: spec/requests/api/v0/follows_spec.rb [hunk 3]
```diff
@@ -1,16 +1,31 @@
 require "rails_helper"
 
 RSpec.describe "Api::V0::FollowsController", type: :request do
+  let_it_be(:user) { create(:user) }
```
Comment (citizen428) [inline spec/requests/api/v0/follows_spec.rb]: Just moved this up here because I'm reusing it in the API key spec.

File: spec/requests/api/v0/github_repos_spec.rb [hunk 4]
```diff
@@ -11,50 +11,71 @@
...
+      api_secret = create(:api_secret, user: user)
+      get api_github_repos_path, headers: { "api-key" => api_secret.secret }
+      expect(response).to have_http_status(:ok)
+    end
+  end
 
-      get api_github_repos_path
-      expect(response).to have_http_status(:unauthorized)
-      expect(response.parsed_body["error"]).to include("Github Unauthorized")
+  context "when user is authorized" do
```
Comment (citizen428) [inline spec/requests/api/v0/github_repos_spec.rb]: Big diff because lots of stuff moved into a new context.

**Comment by citizen428** [comment]
@rhymes Good point, I'll wait for @benhalpern's comment on this. Also, could you quickly check my question regarding `Api::V0::ChatChannelsController` above?

**Comment by rhymes** [comment]
@citizen428 

Think the same applies, it assumes it's only called by the DEV website, I wouldn't expose that to the API just yet. The larger issue is that the moment we expose things to the public API we make a sort of contract, which means we can't break compatibility anymore. I guess these endpoints should be JSON endpoints outside the API controller, as we're doing for the feed stories for example, but it's outside the scope of this PR

**Comment by citizen428** [comment]
Great, thanks for clarifying @rhymes, this was the context I missed. 💯

**Comment by rhymes** [comment]
@citizen428 also, the `ApplicationController` has as `authenticate_user!` exactly for that reason. I'm starting to think that instead of fixing this error we should move those endpoints in `app/controllers` and out of the API...

**Comment by citizen428** [comment]
That does seem to make the most sense, maybe we should fix the root cause instead of papering over the symptoms. I'll defer to Ben on this and if he agrees will update the PR tomorrow.

File: app/controllers/api/v0/github_repos_controller.rb [hunk 5]
```diff
@@ -3,10 +3,12 @@ module V0
     class GithubReposController < ApiController
       include Pundit
 
+      before_action :authenticate_with_api_key_or_current_user!
```
Comment (mstruve) [inline app/controllers/api/v0/github_repos_controller.rb]: Let's use a before_action to require `current_user` for this controller so its not opened up to API key holders and we still get the fix we want.

**Comment by citizen428** [comment]
Ok, sorry for the force push everyone involved in this, but I decided on the following strategy (basically what @mstruve said):

For now I only changed the two controllers mentioned in the original ticket to use 

```ruby
before_action :authenticate_user!
```

This means the specs for the followings controller now cover the actual behavior. I also added the relevant new spec for the GutHub repos controller. 

I'll open a new issue to move over the remaining controllers.
