### PR TITLE
Change sponsorClickHandler to standard function declaration

### LINKED ISSUE #6468: Profile dropdown doesn't open when coming from a mail link
**Describe the bug**
We receive email notifications like new followers etc. When I click on any link on email, it redirects me to DEV website but the profile dropdown doesn't work and also thumbnail disappears. Therefore can't visit Dashboard and other important links.

**To Reproduce**

1. Make sure you are signed into DEV
2. Go to an email of New follower on DEV
3. Click on any link and be redirected to DEV
4. Watch out for Profile thumbnail in navigations right corner

**Expected behavior**

Dropdown is supposed to work.

**Screenshots**

dev-to-profile-dropdown

**Desktop (please complete the following information):**

- OS: macOS
- Browser: Chrome
- Version: 80.0.3987.122 (Official Build) (64-bit)

**Additional context**

A video link explaining the problem:
[https://www.loom.com/share/9ad70239264a4abaa68314ae13b2afe9](https://www.loom.com/share/9ad70239264a4abaa68314ae13b2afe9)

### PR DESCRIPTION
**Pull request by maestromac**
## What type of PR is this? (check all applicable)
- [x] Bug Fix

## Description
My assumption to the cause of bug report #6468 is that the service worker is trying to load our JS asset twice, causing `SyntaxError: redeclaration of const sponsorClickHandler` and break certain portion of the webpage. This is bandaid solution to avoid that particular error.

## Related Tickets & Documents
Hopefully resolves #6468 

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
n/a

## Added tests?
- [x] no, because they aren't needed

## Added to documentation?
- [x] no documentation needed

### CODE REVIEW

File: app/assets/javascripts/initializers/initializeSponsorshipVisibility.js [hunk 1]
```diff
@@ -1,6 +1,4 @@
-'use strict';
-
-const sponsorClickHandler = event => {
+function sponsorClickHandler(event) {
```
Comment (nickytonline) [inline app/assets/javascripts/initializers/initializeSponsorshipVisibility.js]: So using a function instead so it just gets loaded again instead of getting the `VM104:1 Uncaught SyntaxError: Identifier 'sponsorClickHandler' has already been declared`.

This is a nice bandaid solution, but we should investigate why it's being loaded twice.

Comment (nickytonline) [inline app/assets/javascripts/initializers/initializeSponsorshipVisibility.js]: @maestromac, consider adding a comment above this function for now until we figure out the real solution so that someone doesn't refactor this back to `const`.
