### PR TITLE
Nil body_markdown Breaks Article Show Page

### LINKED ISSUE #5965: Nil body_markdown Breaks Article Show Page
This issue is going to require a bit of investigation as I am not sure what causes this to happen but at some point we attempt to render the article show page when the article has a nil `body_markdown`
Honeybadger: https://app.honeybadger.io/fault/66984/93ad9d25eff7baa256b9595ae539dbd0
```
ActionView::Template::Error: undefined method `size' for nil:NilClass
 _actions.html.erb  94 _app_views_articles__actions_html_erb(...)
[PROJECT_ROOT]/app/views/articles/_actions.html.erb:94:in `_app_views_articles__actions_html_erb'
92   </div>
93 </div>
94 <% if @variant_number.to_i == 0 && !user_signed_in? && @article.body_markdown.size > 900 %>
95   <% cache("below-article-html-variant-#{rand(20)}", expires_in: 8.hours) do %>
96     <% @html_variant = HtmlVariant.find_for_test(@article.cached_tag_list_array, "article_show_below_article_cta") %>
```

We should use a safety operator to prevent this from happening or figure out what scenario causes this to happen in the first place and prevent that. 

Additional Errors:
https://app.honeybadger.io/fault/66984/648293b74cbb33fba6e6784c374df50d

### PR DESCRIPTION
**Pull request by abdellani**
## What type of PR is this? 

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
This will prevent users from creating articles having `body_markdown=nil` by editing the payload.
```json
{
  "JSON":{
    "article":{
      "allSeries":[

      ],
      "bodyMarkdown":null,
      "canonicalUrl":"",
      "description":"",
      "edited":true,
      "editing":false,
      "id":null,
      "mainImage":null,
      "organizationId":null,
      "organizations":[

      ],
      "published":true,
      "series":"",
      "submitting":true,
      "tagList":"",
      "title":"dddd",
      "version":"v2"
    }
  }
}
``` 
The response
```json
{
  "Response Payload":{
    "EDITOR_CONFIG":{
      "text":"{\"body_markdown\":[\"is too short (minimum is 0 characters)\"]}",
      "mode":"application/json"
    }
  }
}
```
## Related Tickets & Documents
Fixes #5965 
## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [ ] no documentation needed

### CODE REVIEW

**Comment by abdellani** [comment]
I think that there are some problems with the specifications. 
It seems there is a [scenario](https://github.com/abdellani/dev.to/blob/5965_Nil_body_markdown_Breaks_Article_Show_Page/spec/services/articles/creator_spec.rb#L50) where the body_markdown is set to `nil`, and it expects to get a failure.

While [the test](https://github.com/abdellani/dev.to/blob/5965_Nil_body_markdown_Breaks_Article_Show_Page/spec/services/articles/creator_spec.rb#L63) is failing, the true reason is because of the title was blank and not the `body_markdown`.
```ruby
(byebug) article.errors
#<ActiveModel::Errors:0x00005600e9e50778 @base=#<Article id: nil, user_id: 5, title: nil, body_html: nil, slug: nil, created_at: nil, updated_at: nil, main_image: "https://robohash.org/estdolorumofficiis.png?size=3...", description: "Butcher salvia yolo fixie pour-over roof kickstart...", published: false, password: nil, published_at: nil, featured: false, processed_html: "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.0 Transi...", featured_number: nil, social_image: nil, allow_small_edits: true, allow_big_edits: true, body_markdown: nil, organization_id: nil, canonical_url: nil, collection_id: nil, collection_position: nil, name_within_collection: nil, show_comments: true, main_image_background_hex_color: "#dddddd", ids_for_suggested_articles: "[]", receive_notifications: true, approved: false, amount_due: 0.0, amount_paid: 0.0, paid: false, removed_for_abuse: false, abuse_removal_reason: nil, published_from_feed: false, comments_count: 0, reactions_count: 0, video: nil, video_code: nil, video_source_url: nil, video_thumbnail_url: nil, video_closed_caption_track_url: nil, hotness_score: 0, feed_source_url: nil, main_tag_name_for_social: nil, second_user_id: nil, third_user_id: nil, positive_reactions_count: 0, last_buffered: nil, edited_at: nil, crossposted_at: nil, automatically_renew: false, last_invoiced_at: nil, live_now: false, lat: nil, long: nil, spaminess_rating: 0, language: "en", job_opportunity_id: nil, facebook_last_buffered: nil, cached_tag_list: nil, path: nil, cached_user_name: nil, cached_user_username: nil, last_comment_at: "2017-01-01 05:00:00", email_digest_eligible: true, boost_states: {"boosted_additional_articles"=>false, "boosted_dev_digest_email"=>false, "boosted_additional_tags"=>""}, video_state: nil, reading_time: 0, page_views_count: 0, previous_positive_reactions_count: 0, score: 0, featured_impressions: 0, featured_clickthrough_rate: 0.0, comment_template: nil, video_duration_in_seconds: 0.0, experience_level_rating: 5.0, experience_level_rating_distribution: 5.0, last_experience_level_rating_at: nil, rating_votes_count: 0, originally_published_at: nil, organic_page_views_count: 0, organic_page_views_past_month_count: 0, organic_page_views_past_week_count: 0, cached_user: nil, cached_organization: nil, archived: false, any_comments_hidden: false, nth_published_by_author: 0, comment_score: 0, tag_list: nil>, @messages={:title=>["can't be blank"]}, @details={:title=>[{:error=>:blank}]}>
```

**Comment by abdellani** [comment]
Also, the following specs are failing as they try to create an article without `body_markdown`.
* [./spec/requests/api/v0/articles_spec.rb:477](https://github.com/abdellani/dev.to/blob/5965_Nil_body_markdown_Breaks_Article_Show_Page/spec/requests/api/v0/articles_spec.rb#L477) 
* [./spec/requests/api/v0/articles_spec.rb:483](https://github.com/abdellani/dev.to/blob/5965_Nil_body_markdown_Breaks_Article_Show_Page/spec/requests/api/v0/articles_spec.rb#L483)
* [./spec/requests/api/v0/articles_spec.rb:489](https://github.com/abdellani/dev.to/blob/5965_Nil_body_markdown_Breaks_Article_Show_Page/spec/requests/api/v0/articles_spec.rb#L489)
* [./spec/requests/api/v0/articles_spec.rb:495](https://github.com/abdellani/dev.to/blob/5965_Nil_body_markdown_Breaks_Article_Show_Page/spec/requests/api/v0/articles_spec.rb#L495)

* [./spec/requests/api/v0/articles_spec.rb:504](https://github.com/abdellani/dev.to/blob/5965_Nil_body_markdown_Breaks_Article_Show_Page/spec/requests/api/v0/articles_spec.rb#L504)
* [./spec/requests/api/v0/articles_spec.rb:584](https://github.com/abdellani/dev.to/blob/5965_Nil_body_markdown_Breaks_Article_Show_Page/spec/requests/api/v0/articles_spec.rb#L584)

**Comment by abdellani** [comment]
[./spec/decorators/article_decorator_spec.rb:57](https://github.com/abdellani/dev.to/blob/5965_Nil_body_markdown_Breaks_Article_Show_Page/spec/decorators/article_decorator_spec.rb#L57) is passing locally.

**Comment by abdellani** [comment]
For some reason, when an article is created using `described.call(user,valid_attributes)`, the new object will not contain exactly what is stored in `valid_attributes`.
For example, in this [scenario](https://github.com/thepracticaldev/dev.to/blob/master/spec/services/articles/creator_spec.rb#L17), the `description` changes while "body_markdown" stayes the same : 
```
   15:     it "returns an article" do
   16:       article = described_class.call(user, valid_attributes)
   17:       byebug
=> 18:       expect(article).to be_kind_of(Article)
   19:       expect(article).to be_persisted
   20:     end
   21: 
   22:     it "schedules a job" do
(byebug) valid_attributes[:description]
"Leggings mumblecore muggle magic messenger bag. Austin vinyl celiac truffaut."
(byebug) article.description
"Helvetica gluten-free next level semiotics cornhole green juice cronut flannel. Whatever truffaut kit..."
```
Also, when `invalid_attributes[:body_markdown] == nil`, the article will be generate with `title == nil`.
I found that the change happens when `Article::Creator` call user.save [here](https://github.com/thepracticaldev/dev.to/blob/master/app/services/articles/creator.rb#L52).

I was looking if there are some callback methods that are called before saving a new object in the testing environment but I didn't find anything. Can you please give me some guidance with that problem?

**Comment by mstruve** [comment]
Interesting, seeing as we do a ton of callbacks when we are saving an article such as `evaluate_markdown` and a bunch of others I would look at those and see if one of those is overriding it. Also check the spec for stubbing. We might be stubbing the method for setting the body_markdown or one of the callbacks somewhere.

**Comment by abdellani** [comment]
In the [scenario](https://github.com/abdellani/dev.to/blob/5965_Nil_body_markdown_Breaks_Article_Show_Page/spec/services/articles/creator_spec.rb#L64), `invalid_attributes` doesn't contains a `title`. So the validations will complain about the absence of `title` and `body_markdown`.

The problem, described in my [previous comment](https://github.com/thepracticaldev/dev.to/pull/5982#issuecomment-590067490), comes from `evaluate_front_matter`. The [following line](app/models/article.rb) removes the description coming from `valid_attributes`
```ruby
    self.description = front_matter["description"] if front_matter["description"].present? || front_matter["title"].present? # Do this if frontmatte exists at all
```
And the new description comes [from](https://github.com/abdellani/dev.to/blob/5965_Nil_body_markdown_Breaks_Article_Show_Page/app/models/article.rb#L442) 
```ruby
    self.description = processed_description if description.blank?
```

File: spec/services/articles/creator_spec.rb [hunk 1]
```diff
@@ -51,6 +51,7 @@
     let(:invalid_attributes) { attributes_for(:article) }
 
     before do
+      invalid_attributes[:title] = Faker::Book.title
```
Comment (mstruve) [inline spec/services/articles/creator_spec.rb]: It's a little confusing that we have a valid title in the `invalid_attributes` but the processing of the markdown is also a bit confusing at least to me so I can deal with this. Maybe someone else will have a better suggestion who understands this flow better.

Comment (abdellani) [reply spec/services/articles/creator_spec.rb]: `invalid_attributes` has many valid attributes, the only invalid one is `body_markdown`.

Comment (vaidehijoshi) [reply spec/services/articles/creator_spec.rb]: We could change this from `invalid_attributes` to `invalid_body_attributes` to make this more explicit.

File: spec/requests/api/v0/articles_spec.rb [hunk 2]
```diff
@@ -475,27 +475,27 @@ def post_article(**params)
       end
 
       it "creates an article belonging to the user" do
-        post_article(title: Faker::Book.title)
+        post_article(title: Faker::Book.title, body_markdown: "")
```
Comment (vaidehijoshi) [inline spec/requests/api/v0/articles_spec.rb]: Since we are adding this as an argument as a default for `post_article` in a few different places, we might consider creating a default params object at the top of these tests with the empty (but valid) `body_markdown`, and then using that inside of the `post_article` method that is defined on line `454`. Alternatively, we could also just set a defaults for `body_markdown` and pass that in as `params: { article: params }`, but also allow it to be overridden.

To be clear, I don't think should block this PR by any means, just figured it would be a nice way to clean this up since we're doing a lot of the same changes in this spec :)
