### PR TITLE
Fixed regex for Spotify playlist

### LINKED ISSUE #2739: Error trying to embed Spotify playlists URIs
**Describe the bug**
Trying to embed a Spotify playlist URI gives and error

**To Reproduce**
Example code:
```
{% spotify spotify:user:spotify:playlist:37i9dQZF1E36t2Deh8frhL %}
```

1. Go to 'Write post'
2. Insert the example code
3. Click 'save post' or 'Preview'

**Expected behavior**
Embed the URI the same way with albums, tracks, etc.

**Screenshots**
screen capture

**Additional context**
https://github.com/thepracticaldev/dev.to/issues/1546#issuecomment-490039164

### PR DESCRIPTION
**Pull request by Glennmen**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Documentation Update

## Description
So I had to do a couple of changes to make the Spotify liquid tag work correctly again.

* I had to remove `user`, it seems that this doesn't work with the same embed URL but has it's own URL. This would require bigger changes that I think are out of scope for this PR, link to source: https://developer.spotify.com/documentation/widgets/generate/follow-button/

* I added `show`, this adds support for podcast shows.

* I also added a new regex to support playlists from users. This required changed in a couple of places to correctly support multiple regexes.

* Fixed heights, I based the heights on the defaults from Spotify. Source: https://developer.spotify.com/documentation/widgets/generate/play-button/

* Also added a new test to check the Spotify playlist uri

## Related Tickets & Documents
Fixes #2739 

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)
Spotify track

Spotify artist

Spotify album

Spotify episode

Spotify show

Spotify playlist

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

music

### CODE REVIEW

File: app/liquid_tags/spotify_tag.rb [hunk 1]
```diff
@@ -29,7 +32,7 @@ def render(_context)
   private
 
   def parse_uri(uri)
-    URI_REGEXP.match(uri) || raise_error
+    Regexp.union(URI_REGEXP, URI_PLAYLIST_REGEXP).match(uri) || raise_error
```
Comment (rhymes) [inline app/liquid_tags/spotify_tag.rb]: didn't know about `Regexp.union`, so cool!

Comment (Glennmen) [reply app/liquid_tags/spotify_tag.rb]: Me neither 😂 everything in Ruby is new to me so making this PR took more time than I expected.
