### PR TITLE
Use named function so duplicate event handlers are discarded

### LINKED ISSUE #4571: Profile Menu does not open at some certain situations
**Describe the bug**
When you navigate to page from a profile menu it works correctly the first time but when you try to navigate again the menu does not open.
(Sorry this is kind of difficult to explain I've attached a video below to explain better)

I've described it better below in steps to reproduce and the video

**To Reproduce**
(I've also attached a video below to explain this)

1. Open main page (https://dev.to) 
2. Click profile picture
3. Select your username from navigation
4. Now If you try to click on your profile picture again it will not open the navigation.

**Expected behavior**

**Screenshots**
GIF Explaining the Menu Bug

**Desktop (please complete the following information):**

- OS: Ubuntu 19
- Browser: Chrome
- Version: 77.0.3865.120 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

- Device: Motorola One Power
- OS: Android Pie
- Browser: Chrome
- Version: 77.0.3865.116

**Additional context**
I've tried this on both Android and Desktop and even on the Android App and the results were same. There weren't any additional errors in the console.

### PR DESCRIPTION
**Pull request by jennapederson**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Documentation Update

## Description

Multiple event listeners were being added to the navigation button. Changed to add a named function instead of anonymous so that duplicates are discarded.

Looks like the system tests are only running with desktop chrome browser, so I've not made any updates there.

## Related Tickets & Documents

Fixes #4571 

## Mobile & Desktop Screenshots/Recordings (if there are UI changes)

n/a

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

File: app/assets/javascripts/initializers/initializeTouchDevice.js [hunk 1]
```diff
@@ -37,9 +41,7 @@ function initializeTouchDevice() {
   setTimeout(() => {
     removeShowingMenu();
     if (isTouchDevice) {
-      getById('navigation-butt').addEventListener('click', e =>
-        getClassList('navbar-menu-wrapper').toggle('showing'),
-      );
+      getById('navigation-butt').addEventListener('click', toggleMenu);
```
Comment (rhymes) [inline app/assets/javascripts/initializers/initializeTouchDevice.js]: I love this change, but, since I know how human minds work, in a six months time this could become again an anonymous function for any reason. Would you be willing to prepend this line with a comment explaining the reason why? Basically on the same notes of what you wrote in the issue description. Thank you very much!

Comment (jennapederson) [reply app/assets/javascripts/initializers/initializeTouchDevice.js]: Done. Good call!
