### PR TITLE
Fix raising validation if followable already exist(race condition)

### LINKED ISSUE #5793: Return "followed" result if Followable already Exists Instead of Raising a Validation Error
In the follows controller when we try to create a follow, sometimes the validation fails bc it already exists. This is a pretty common occurrence and likely due to hitting the button twice or some front end race condition. 
Honeybadger: https://app.honeybadger.io/fault/66984/b9e5567612f10d6a9413da94444f6458
Error:
```
ActiveRecord::RecordInvalid: Validation failed: Followable has already been taken
monitor.rb  235 mon_synchronize(...)
[PROJECT_ROOT]/vendor/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
233     Thread.handle_interrupt(EXCEPTION_NEVER){ mon_enter }
234     begin
235       yield
236     ensure
237       Thread.handle_interrupt(EXCEPTION_NEVER){ mon_exit }
```

I believe, in the event that a follow already exists, we should exit early and return the result "followed".  If anyone has other thoughts on that approach let me know!

### PR DESCRIPTION
**Pull request by gonzar11**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
It rescues from  ActiveRecord::RecordInvalid assuming that it only be raised in case that we have a race condition trying to create the same Follow model from different threads/request.

## Related Tickets & Documents
closes #5793

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?
My first contribution to an open source project.
alt_text

### CODE REVIEW

File: app/controllers/follows_controller.rb [hunk 1]
```diff
@@ -68,7 +68,11 @@ def follow_params
   end
 
   def follow(followable, need_notification: false)
-    user_follow = current_user.follow(followable)
+    begin
+      user_follow = current_user.follow(followable)
+    rescue ActiveRecord::RecordInvalid => e
+      Rails.logger.error(e)
```
Comment (citizen428) [inline app/controllers/follows_controller.rb]: We may want to do more than just log an error here, e.g. update a DataDog metric. @mstruve can point you in the right direction.

File: app/controllers/follows_controller.rb [hunk 2]
```diff
@@ -68,7 +68,11 @@ def follow_params
   end
 
   def follow(followable, need_notification: false)
```
Comment (citizen428) [inline app/controllers/follows_controller.rb]: `def` is an implicit `begin`, so this could be:

```ruby
def follow(followable, need_notification: false)
  user_follow = current_user.follow(followable)
rescue ActiveRecord::RecordInvalid => e
  Rails.logger.error(e)
end
```

See e.g. https://www.rubyguides.com/2019/06/ruby-rescue-exceptions/

Comment (gonzar11) [reply app/controllers/follows_controller.rb]: Thank you @citizen428 . I am seeing that codeclimate/diff-coverage check failed. How can I do to turn this check in green?

Comment (rhymes) [reply app/controllers/follows_controller.rb]: unfortunately the report is not very forthcoming on details, so I think you can ignore it :)

File: app/controllers/follows_controller.rb (hunk 1 above)
Comment (mstruve) [reply app/controllers/follows_controller.rb]: I'm torn. I don't really think it is that important but at the same time, I have learned when in doubt log it so let's do `DataDogStatsClient.increment("users.invalid_follow")` instead of Rails.logger here to track it on the off chance we want the metric in the future for some reason.

File: app/controllers/follows_controller.rb [hunk 3]
```diff
@@ -68,7 +68,11 @@ def follow_params
...
-    user_follow = current_user.follow(followable)
+    begin
+      user_follow = current_user.follow(followable)
+    rescue ActiveRecord::RecordInvalid => e
+      Rails.logger.error(e)
+    end
     Notification.send_new_follower_notification(user_follow) if need_notification
```
Comment (mstruve) [inline app/controllers/follows_controller.rb]: I think we should add this to our happy path/begin block since we know if the follow is invalid we dont need to send a notification.

File: app/controllers/follows_controller.rb (hunk 2 above)
Comment (gonzar11) [reply app/controllers/follows_controller.rb]: @citizen428 If I don't use begin keyword then I have to use return statement  in ensure block. Is this ok for you?
```
def follow(followable, need_notification: false)
  user_follow = current_user.follow(followable)
rescue ActiveRecord::RecordInvalid => e
  DataDogStatsClient.increment("users.invalid_follow")
ensure
   Notification.send_new_follower_notification(user_follow) if need_notification
   return "followed"
end
```

Comment (mstruve) [reply app/controllers/follows_controller.rb]: I would set it up like this and actually I think that reads pretty cleanly personally. We will see what @citizen428 thinks. 
```ruby
def follow(followable, need_notification: false)
  user_follow = current_user.follow(followable)
  Notification.send_new_follower_notification(user_follow) if need_notification
rescue ActiveRecord::RecordInvalid => e
  DataDogStatsClient.increment("users.invalid_follow")
ensure
   return "followed"
end
```

File: app/controllers/follows_controller.rb (hunk 1 above)
Comment (citizen428) [reply app/controllers/follows_controller.rb]: Tbh, I wasn't sure either, hence the "we may want to do more". But like you I lean in the direction of logging more.

File: app/controllers/follows_controller.rb (hunk 2 above)
Comment (citizen428) [reply app/controllers/follows_controller.rb]: I'm not sure if we should really return "followed" in case something went wrong. Maybe just have different returns based on whether we succeed or fail?

```ruby
def follow(followable, need_notification: false)
  user_follow = current_user.follow(followable)
  Notification.send_new_follower_notification(user_follow) if need_notification
  "followed"
rescue ActiveRecord::RecordInvalid => e
  DataDogStatsClient.increment("users.invalid_follow")
  # some other message, e.g. "previously followed"
end
```

Either way, it's such a small detail I'll leave it to your judgement what you think is best, i.e. if you want to keep as-is, I have no problem with that.

Comment (gonzar11) [reply app/controllers/follows_controller.rb]: Thank you folks for your help. I ended up removing `ensure` because Rubocop doesn't like to have a `return` within `ensure`.

**Comment by mstruve** [comment]
I know I approved it but it would probably be a good idea to add a spec for the new failure mode

**Comment by gonzar11** [comment]
> I know I approved it but it would probably be a good idea to add a spec for the new failure mode

I thought about that but I couldn't figure out how to simulate this race condition.  Do you mean by making request from multiple thread?

**Comment by mstruve** [comment]
I was thinking by creating one and then attempting to use this endpoint to create a second immediately after. But I can live without it :)

**Comment by mstruve** [comment]
Oh one last thing, did you sign the CLA?

**Comment by gonzar11** [comment]
> Oh one last thing, did you sign the CLA?

I did it :)
