### PR TITLE
fix scrollheight calculation by using scrollable element instead of document element

### LINKED ISSUE #1805: Posts on front page do not load until scrolled down
When going to the home page, sometimes posts under the first post do not load until you scroll down. The page simply hangs and looks like this:
image 1

This seems to happen on Windows 10, Chrome. Possibly related extension is uBlock Origin.

I think that we load the posts with Algolia, so there might be some JS that is triggered by scrolling. Not 100% sure though.

### PR DESCRIPTION
**Pull request by colbymelvin**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Documentation Update

## Description
Fixes #1805 by changing scrollHeight calculation in initScrolling to use the actual scrollable element vs. the document element.

Re-submission of https://github.com/thepracticaldev/dev.to/pull/4247. Initial commit in that PR was made without having my git identity setup (new laptop). This re-submission is simply to associate my git identity with the commits to satisfy CLA Assistant.

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

File: app/assets/javascripts/initializers/initScrolling.js.erb [hunk 1]
```diff
@@ -24,21 +24,38 @@ function checkIfNearBottomOfPage() {
...
+  } else {
+    scrollableElemId = "articles-list";
+    fetchCallback = function() {
+      algoliaPaginate(indexContainer.dataset.algoliaTag);
+    };
+  }
+
+  var scrollableElem = document.getElementById(scrollableElemId);
+
+  if ( !done && !fetching && (window.scrollY) > (scrollableElem.scrollHeight - 3700) ) {
```
Comment (colbymelvin) [inline app/assets/javascripts/initializers/initScrolling.js.erb]: This line is the meat - previously we were using the document element in this calculation. That's a problem when the sidebar has a considerable amount of content. When the height of the sidebar reaches a certain threshold, it impacts this calculation.

File: app/assets/javascripts/initializers/initScrolling.js.erb [hunk 2]
```diff
@@ -24,21 +24,38 @@ function checkIfNearBottomOfPage() {
...
+    scrollableElemId = "video-collection";
+    fetchCallback = function() {
+      fetchNextVideoPage(indexContainer);
+    };
+  } else {
+    scrollableElemId = "articles-list";
+    fetchCallback = function() {
+      algoliaPaginate(indexContainer.dataset.algoliaTag);
+    };
+  }
```
Comment (colbymelvin) [inline app/assets/javascripts/initializers/initScrolling.js.erb]: I needed these conditionals on `indexWhich` to determine which scrollable element I should be looking for. Instead of duplicating the conditionals again below to determine which index action should be taken, I just pulled the conditionals out here and defined a `fetchCallback`.

File: app/assets/javascripts/initializers/initScrolling.js.erb (hunk 1 above)
Comment (pavelloz) [inline app/assets/javascripts/initializers/initScrolling.js.erb]: This module probably hurts performance in a meaningful way because it is accessing properties triggering layout recalculation.

[Read more](https://gist.github.com/paulirish/5d52fb081b3570c81e3a)


I would suggest looking at [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) for detection of element within the current viewport.

**Comment by pavelloz** [comment]
This module probably hurts performance in a meaningful way because it is accessing properties triggering layout recalculation.

[Read more about layout trashing](https://gist.github.com/paulirish/5d52fb081b3570c81e3a)

I would suggest looking at [IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) for detection of element within the current viewport.

**Comment by colbymelvin** [comment]
@maestromac Are you following any tags in your local environment? It looks like`initializeFetchFollowedArticles.js.erb` only fetches articles on the home page if so (line 138). This may be a bug in and of itself. 

 I think the best way that I've found to test this is:

1. ensure you are not following any tags,
2. in this branch, short-circuit line 56 of `app/assets/javascripts/initializers/initScrolling.js.erb` to return `false`
3. verify you see the hanging on the home page
4. undo the change made in # 2 
5. verify you don't see the hanging on the home page

**Comment by rhymes** [comment]
@pavelloz would you be willing to promote your comment to a separate issue explaining the what and why? Otherwise I fear we'd lose precious information on how to improve the code. Thank you!
