### PR TITLE
[MarkdownFixer] Do not escape username with underscores in code or codeblocks

### LINKED ISSUE #5739: Code snippet rendering issue related to underscore
Hey dev 👋 

Reporting a bug.

**Describe the bug**

There is `\` present in rendered code block.

**To Reproduce**

Have this code snippet in your post

```ruby
def init_internals
  @primary_key              = self.class.primary_key
  @readonly                 = false
  @destroyed                = false
  @marked_for_destruction   = false
  @destroyed_by_association = nil
  @_start_transaction_state = nil
  @transaction_state        = nil

  self.class.define_attribute_methods
end
```

**Expected behavior**

As GitHub renders above. Without seeing `\` in rendered code block. 

**Screenshots**

スクリーンショット 2020-01-27 17 37 20

Best,
Juanito

### PR DESCRIPTION
**Pull request by JuanitoFatas**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [x] Tests are passing 

  ```shell
  bundle exec rspec spec/labor/markdown_fixer_spec.rb spec/requests/api/v0/articles_spec.rb spec/services/articles/creator_spec.rb spec/services/mentions/create_all_spec.rb
  ```
- [x] I‘ve verified it works on development
  starts the server at local, sign in, new post, copy the following to preview and see if things work as expected. You should not see `\` in code and codeblock, and underscored username renders correctly.
  <details>
  <summary>Code for testing at development</summary>

  <pre>
  @_dev_

  ```
  @_dev_
  ```

  `@_dev_`

  @_dev_
  </pre>
  </details>

## Description

The underscored username got escaped in code and code blocks. We probably do not want that. The fix is only to escape underscored username if they are not in code or code blocks.

Other possible approaches:

- Write regexp that only pull out underscored usernames not in code or code blocks
- Turn markdown into HTML and use Nokogiri to work on text of ancestors not `pre` or `code`

## Related Tickets & Documents

Fixes #5739.  

### Current on dev (2019.01.28, 26e4412)

スクリーンショット 2020-01-28 17 41 26

### After this Pull Request (tested against 432885f)

スクリーンショット 2020-02-09 22 49 42

スクリーンショット 2020-02-09 22 36 07

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed
- [x] code comments added

### CODE REVIEW

**Comment by Zhao-Andy** [comment]
I assume this PR is good because all tests are passing now, but @JuanitoFatas let me know if I'm mistaken. :)

**Comment by JuanitoFatas** [comment]
@Zhao-Andy 

> I assume this PR is good because all tests are passing now, but @JuanitoFatas let me know if I'm mistaken. :)

Rebased with master and verified it works ✅ 

スクリーンショット 2020-02-04 09 27 52

and tests passed 🎉 

スクリーンショット 2020-02-04 09 32 22

:shipit:

File: app/labor/markdown_fixer.rb [hunk 1]
```diff
@@ -47,7 +68,28 @@ def split_tags(markdown)
...
+
+        if walker.in_codeblock?
+          line
+        else
+          escape_underscored_username_in_line!(line)
+        end
+      end.join
+    end
+
+    USERNAME_WITH_UNDERSCORE_REGEXP = /(?<!`)@_\w+_/.freeze
```
Comment (rhymes) [inline app/labor/markdown_fixer.rb]: can we add a comment that narrates this regexp? As it's not particularly intuitive

**Comment by JuanitoFatas** [comment]
@rhymes 

Thanks for the review. I‘ve added comments and changed the implementation to a less clever one 😉 . I also pulled the node traverser into a separate file, hope that make it easier to read. Verified this works and updated the screenshot in the Pull Request accordingly 🎉

File: app/labor/markdown_fixer.rb [hunk 2]
```diff
@@ -47,11 +47,29 @@ def split_tags(markdown)
     end
 
     def underscores_in_usernames(markdown)
-      markdown.gsub(/(@)(_\w+)(_)/, '\1\\\\\2\\\\\3')
+      return markdown unless markdown.include?("@")
```
Comment (citizen428) [inline app/labor/markdown_fixer.rb]: This guard clause has to go through all of `markdown` to determine whether or not to return, so I don't think it saves us much work. If we skip this check we go through the document once, if we keep it we go through the document once + the percentage of text preceding the username.

File: app/labor/markdown_fixer.rb [hunk 3]
```diff
@@ -47,11 +47,29 @@ def split_tags(markdown)
...
+
+      traverser = MarkdownTraverser.new(markdown)
+      traverser.each do |line|
+        unless traverser.in_codeblock?
```
Comment (citizen428) [inline app/labor/markdown_fixer.rb]: How about 

```ruby
next if traverser.in_codeblock?
escape_underscored_username_in_line!(line)
```

File: app/labor/markdown_fixer.rb [hunk 4]
```diff
@@ -47,11 +47,29 @@ def split_tags(markdown)
...
     end
 
     private
 
+    # Match @_username_ that is not preceded by backtick
+    USERNAME_WITH_UNDERSCORE_REGEXP = /(?<!`)@_\w+_/.freeze
+
+    # Escapes underscored username that is not in code
+    def escape_underscored_username_in_line!(line)
+      line.scan(USERNAME_WITH_UNDERSCORE_REGEXP).each do |to_escape|
```
Comment (citizen428) [inline app/labor/markdown_fixer.rb]: Instead of `scan` + `each` and then explicitly returning `line`, could we use the block form of `gsub` here? Something like (untested)

```ruby
line.gsub(USERNAME_WITH_UNDERSCORE_REGEXP) { |to_escape| to_escape.gsub("_", "\\_") }
```

File: app/labor/markdown_traverser.rb [hunk 5]
```diff
@@ -0,0 +1,35 @@
...
+    end
+  end
+
+  def in_codeblock?
+    prev == true && current == false
+  end
+
+  private
+
+  CODEBLOCK_MARKER = "```".freeze
```
Comment (citizen428) [inline app/labor/markdown_traverser.rb]: Not that the visibility of this matters much, just checking in to see if you're aware that moving constants in a `private` block will not actually make them private, you need the `private_constant` method for that.

File: app/labor/markdown_fixer.rb (hunk 2 above)
Comment (JuanitoFatas) [reply app/labor/markdown_fixer.rb]: There are number of tests that pass `""`, front matters, or text that do not have username at all (without `@`) to here. These make sense in real world. Hence checking for `@` here to avoid doing work for irrelevant cases and all tests are happy.

File: app/labor/markdown_fixer.rb (hunk 3 above)
Comment (JuanitoFatas) [reply app/labor/markdown_fixer.rb]: Sure 👍

File: app/labor/markdown_fixer.rb (hunk 4 above)
Comment (JuanitoFatas) [reply app/labor/markdown_fixer.rb]: I would like this too, but the `line` could be

```text
@_dev_ `@_dev_`
```

hence we cannot replace all underscores in a line.

File: app/labor/markdown_traverser.rb (hunk 5 above)
Comment (JuanitoFatas) [reply app/labor/markdown_traverser.rb]: Yup 👍

File: app/labor/markdown_fixer.rb (hunk 4 above)
Comment (citizen428) [reply app/labor/markdown_fixer.rb]: This is not replacing all underscores in a line, this is replacing all underscores in  every `to_escape`, which is everything that matches `USERNAME_WITH_UNDERSCORE_REGEXP`:

```ruby
line = '@_dev_ `@_dev_`'
line.gsub(USERNAME_WITH_UNDERSCORE_REGEXP) { |to_escape| to_escape.gsub("_", "\\_") }
#=> "@\\_dev\\_ `@_dev_`"
```

Isn't this what you want, i.e. escape the username outside backticks but leave the one inside unchanged?

File: app/labor/markdown_fixer.rb (hunk 2 above)
Comment (citizen428) [reply app/labor/markdown_fixer.rb]: I understand that the check makes sense, but I think the way it's currently done is slightly inefficient. You already walk the document in the traverser, you could just ignore lines without an `@`, so you only walk the document a total of 1 time. Was that a bit clearer?

Comment (citizen428) [reply app/labor/markdown_fixer.rb]: I understand the reason for the check, my only slight concern was that in articles that contain usernames we actually do slightly more work (first read `markdown` until we find an `@`, then traverse it), but given that the majority of articles will probably not have usernames in them this seems like a good solution.

Comment (JuanitoFatas) [reply app/labor/markdown_fixer.rb]: Hey checking against the regexp makes sense. I‘ve updated the code.

File: app/labor/markdown_fixer.rb (hunk 4 above)
Comment (JuanitoFatas) [reply app/labor/markdown_fixer.rb]: Sorry I overlooked from my last comment. But I did give this a try and other places need to modify as well but I don‘t have time to look into why this does not work. What‘s your concern on the current implementation? I‘m happy to receive a PR against this feature branch.

Comment (citizen428) [reply app/labor/markdown_fixer.rb]: No concern, it just seemed like it's using a more complicated approach than necessary. I'll trust you if you say it doesn't work, so let's just leave it as is.
