### PR TITLE
Fix #5072: Remove unnecessary reaction call

### LINKED ISSUE #5072: Reaction Creation Fails due to missing Reactable ID
**Describe the bug**
There is some spot in the codebase(pretty sure its in the front end javascript) where we are attempting to update a Reaction record but we do not send sufficient data and we end up with this error. 
```
ActiveRecord::RecordInvalid: Validation failed: Reactable must exist, Reactable is not valid.
```
This error is raised on line 58 of the reactions controller and is due to the following params being sent.
```ruby
# Line number: /app/controllers/reactions_controller.rb:58:in `create'
# Params: {
#  "reactable_type" => "Article",
#  "reactable_id" => "undefined",
#  "category" => "readinglist"
# }
reaction = Reaction.create!(
        user_id: current_user.id,
        reactable_id: params[:reactable_id],
        reactable_type: params[:reactable_type],
        category: category,
      )
```
**To Reproduce**

Not sure. The referrer url from all the Honeybadgers we are seeing is a search url like `https://dev.to/search?q=something`

**Expected behavior**

We should either populate the reactable_id correctly or not send the request at all if the field is not populated

### PR DESCRIPTION
**Pull request by matheusazzi**
What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Inside the [search result page](https://dev.to/search?q=test&filters=class_name:User), when you select to search by people on the sidebar and click the button to follow someone, it was erroneously triggering a reaction ajax request, thus not having the `reactable_id`:

Group
_If you click any of those follow buttons you'll see the failed ajax request on console._

It gets called because all buttons with the `bookmark-engage` class get that event assigned to it. And the follow buttons use that class too, probably only to have the same styling. 

There are many ways to solve this problem, I've updated the CSS classes in a way those buttons have a common styling class `.engage-button` to look the same. Then, the event for the "reactions" is only added to the existing `.bookmark-button` class and the following buttons won't use it anymore.

The request for following/unfollowing the person still occurs as usually.

## Related Tickets & Documents
- Fixes https://github.com/thepracticaldev/dev.to/issues/5072

### CODE REVIEW

File: app/assets/javascripts/initializers/initializeAllFollowButts.js [hunk 1]
```diff
@@ -9,7 +9,6 @@ function initializeAllFollowButts() {
 
 function initializeFollowButt(butt) {
   var user = userData();
-  var deviceWidth = window.innerWidth > 0 ? window.innerWidth : screen.width;
```
Comment (matheusazzi) [inline app/assets/javascripts/initializers/initializeAllFollowButts.js]: Unused variable.

**Comment by benhalpern** [comment]
I think this is all good. But let me revisit this in the morning before deploying because I want to think through any possible rollout issues with caching. So I'll revisit it tomorrow and get it shipped once I give it fresh mind.
