### PR TITLE
Fix/events show 404

### LINKED ISSUE #5795: Return a 404 response If @event is Not Found
In the events controller we lookup the requested event. However, since we are using `find_by` if the event is not found we simply try to load the view with a nil `@event` which leads to the error below
```ruby
def show
  @event = Event.find_by(slug: params[:id])
end
```
Honeybadger: https://app.honeybadger.io/fault/66984/b5b494606dbf78f0e09c009ea5e1e627
Error:
```
ActionView::Template::Error: undefined method `title' for nil:NilClass
show.html.erb  2 block in _app_views_events_show_html_erb__3248125032052569105_140759860(...)
[PROJECT_ROOT]/app/views/events/show.html.erb:2:in `block in _app_views_events_show_html_erb__3248125032052569105_140759860'
1 <%= content_for :page_meta do %>
2   <% title "#{@event.title} - DEV" %>
3   <link rel="canonical" href="https://dev.to/<%= @event.slug %>" />
4   <meta name="description" content="dev.to | Events">
```

In the event that an `@event` is not found we should return a `not_found` status. ApplicationController has a handy `not_found` method that you can use to do this. I think you will want to implement a solution similar [to this one](https://github.com/thepracticaldev/dev.to/pull/5646/files#diff-cae59de326d9d5bfb471bb23bbd25c1fR62).

### PR DESCRIPTION
**Pull request by Zeko369**
## What type of PR is this? (check all applicable)

- [x] Refactor
- [ ] Feature
- [X] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Return 404 if event is not found instead of getting an error

## Related Tickets & Documents
closes #5795 

## Added to documentation?

- [ ] docs.dev.to
- [ ] readme
- [x] no documentation needed

### CODE REVIEW

File: app/controllers/events_controller.rb [hunk 1]
```diff
@@ -11,5 +11,6 @@ def index
 
   def show
     @event = Event.find_by(slug: params[:id])
+    not_found unless @event
```
Comment (rhymes) [inline app/controllers/events_controller.rb]: As `not_found` raises `ActiveRecord::RecordNotFound` I think it'd be better and more "Rails-y" to just use `.find_by!` in Rails which raises `ActiveRecord::RecordNotFound` by itself: https://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html#method-i-find_by-21

My suggestion is to simply do:

```ruby
@event = Event.find_by!(slug: params[:id])
```
