### PR TITLE
Strip org secret before searching and add better error handling for invalid secrets

### LINKED ISSUE #2828: 404 error When Trying to Join Org
**Describe the bug**
A user attempted to join an organization using a provided secret code, but received a 404 when trying. They tried to create a new account but received the same result.

**Expected behavior**
A user should be able to easily join an org when invited.

**Additional context**
I've not provided any account information for privacy reasons.

### PR DESCRIPTION
**Pull request by Zhao-Andy**
## What type of PR is this? (check all applicable)
- [x] Bug Fix

## Description
Sometimes the `org_secret` parameter has an extra space. This PR removes any whitespace.

Also, we currently send a 404 response if the submitted `org_secret` is invalid. This PR redirects the user back to `/settings/organization` and shows an error message instead.

Resolves #2828

### CODE REVIEW

File: app/controllers/users_controller.rb [hunk 1]
```diff
@@ -110,15 +110,16 @@ def onboarding_update
...
       ActiveRecord::Base.transaction do
         current_user.update(organization_id: @organization.id)
         OrganizationMembership.create(user_id: current_user.id, organization_id: current_user.organization_id, type_of_user: "member")
       end
       redirect_to "/settings/organization",
                   notice: "You have joined the #{@organization.name} organization."
     else
-      not_found
+      flash[:error] = "The given organization secret was invalid."
+      redirect_to "/settings/organization"
```
Comment (Zhao-Andy) [inline app/controllers/users_controller.rb]: I used `redirect_to` instead of `render`  because rendering would require getting all the instance variables, and also for some reasons the styles weren't loaded with  `render`.

File: app/controllers/users_controller.rb [hunk 2]
```diff
@@ -110,15 +110,16 @@ def onboarding_update
 
   def join_org
     authorize User
-    if (@organization = Organization.find_by(secret: params[:org_secret]))
+    if (@organization = Organization.find_by(secret: "params[:org_secret].strip"))
```
Comment (rhymes) [inline app/controllers/users_controller.rb]: I think the quotes here should be removed

Comment (Zhao-Andy) [reply app/controllers/users_controller.rb]: Ooh yes, good catch. I was debugging 😅 
```suggestion
    if (@organization = Organization.find_by(secret: params[:org_secret].strip))
```
