### PR TITLE
Don't Allow Users To React to Unpublished Posts

### LINKED ISSUE #5959: Don't Allow Users To React to Unpublished Posts
When a user attempts to reaction to an unpublished post we end up with this error
Honeybadger: https://app.honeybadger.io/fault/66984/960bfd4e2872007d5267d0a0bbaf1660
Error:
```
ActiveRecord::RecordInvalid: Validation failed: Reactable is not valid.
[PROJECT_ROOT]/vendor/ruby-2.6.5/lib/ruby/2.6.0/monitor.rb:235 :in `mon_synchronize`
233     Thread.handle_interrupt(EXCEPTION_NEVER){ mon_enter }
234     begin
235       yield
236     ensure
237       Thread.handle_interrupt(EXCEPTION_NEVER){ mon_exit }
[PROJECT_ROOT]/app/controllers/reactions_controller.rb:58 :in `create`
```

Possible Solutions: Rather than throwing an error and having it logged in Honeybadger we should not allow the user to click on those reaction buttons until the post is published. OR we check to see if the post is published prior to attempting to make the reaction. I think the first option is the way to go but feel free to poke around and see if you find something better! 

Steps to reproduce: 
Create a draft of an article. View the draft and click on any of the reaction buttons. You will see the error pop up in your logs.

### PR DESCRIPTION
**Pull request by abdellani**
## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Instead of creating Reaction using `create!`, I use `new` then I check if the reaction can be saved    
## Related Tickets & Documents
Fixes #5959

### CODE REVIEW

File: app/controllers/reactions_controller.rb [hunk 1]
```diff
@@ -48,24 +48,27 @@ def create
...
     else
-      reaction = Reaction.create!(
+      reaction = Reaction.new(
         user_id: current_user.id,
         reactable_id: params[:reactable_id],
         reactable_type: params[:reactable_type],
         category: category,
       )
-      @result = "create"
+      return render json: { error: reaction.errors.full_messages.join(", "), status: 422 }, status: :unprocessable_entity unless reaction.save
```
Comment (rhymes) [inline app/controllers/reactions_controller.rb]: this is a really obfuscated guard that also contains a side effect (the saving), in addition to being a really long line visually, what about:

```ruby
if reaction.save
else
end
```

?

**Comment by abdellani** [comment]
@rhymes 
if I remove the guard clause, Rubocop complains about nested conditions.

File: app/views/articles/_actions.html.erb [hunk 2]
```diff
@@ -1,20 +1,22 @@
...
-    <img alt="reading list" src="<%= asset_path("emoji/emoji-one-bookmark.png") %>" /><span class="reaction-number" id="reaction-number-readinglist"></span>
-  </button>
-  <a class="article-actions-tweet-button"
-     id="article-actions-tweet-button"
-     rel="noopener"
-     target='_blank'
-     href='https://twitter.com/intent/tweet?text="<%= u @article.title.strip %>" by <%= @article.user.twitter_username ? "@" + @article.user.twitter_username : @article.user.name %> %23DEVcommunity https://dev.to<%= @article.path %>'>
-    <img src="<%= asset_path("twitter.svg") %>" alt="twitter logo">
-  </a>
+  <% if @article.published? %>
```
Comment (Zhao-Andy) [inline app/views/articles/_actions.html.erb]: Now that I think about it more, if a user has a published post that they decide to unpublish in the future, they won't see the previous reactions anymore. I think because of this scenario we'll want to keep the reactions sidebar there. Or you could change the boolean to:
```
if @article.published? || @article.positive_reactions_count.positive?
```

Comment (mstruve) [reply app/views/articles/_actions.html.erb]: @Zhao-Andy in this case I think it is easier to hide the reactions rather than showing them and worrying about disabling them.

**Comment by maestromac** [comment]
Something's wrong with the checks. I'm going to close and re-open this PR in the hope that it will kick off the checks.

**Comment by mstruve** [comment]
I think we can ignore the code climate one,
