### PR TITLE
Fix liquid tag parsing error

### LINKED ISSUE #1472: Twitter liquid tag displays error instead of embedded tweet
**Describe the bug**
Embedded tweets won't preview or display when a blog post is saved.

**To Reproduce**

1. Create a new post (doesn't need to be published) and add a Twitter liquid tag, e.g. `{%twitter 970335487071342593 %}`
2. Preview the post. Where the embedded Tweet should be is an error `Liquid error: internal`

**Expected behavior**
An embedded tweet should appear where a liquid tag is located in markdown when in Preview and/or when viewing a saved blogpost.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mac 10.14.2
- Browser Chrome
- Version 1.0.3578.98 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by maestromac**
## What type of PR is this? (check all applicable)
- [x] Bug Fix

## Description
Liquid tag error is caused by `TweetTag`'s inability to use `#image_tag`. Including the proper view helper should fixes it.

## Related Tickets & Documents
resolves #1472 

## Added to documentation?
- [x] no documentation needed

### CODE REVIEW

File: spec/liquid_tags/tweet_tag_spec.rb [hunk 1]
```diff
@@ -16,6 +16,13 @@ def generate_tweet_liquid_tag(id)
     end
   end
 
+  it "render properly", :vcr do
+    VCR.use_cassette("twitter_gem") do
+      liquid = generate_tweet_liquid_tag(twitter_id)
+      expect(liquid.render).not_to eq("liquid error: internal")
```
Comment (abraham) [inline spec/liquid_tags/tweet_tag_spec.rb]: It would be better to test for the expected working text, if the error message was to change at some point this test would no longer provide any assurances.

Comment (maestromac) [reply spec/liquid_tags/tweet_tag_spec.rb]: You are right. Updating.
