### PR TITLE
Validate that API article params are a Hash

### LINKED ISSUE #5957: Validate That API Article Params are Hash, If not return helpful error message
Sometimes people hit the API with invalid params such as 
```
{ "article" => "body_markdown" }
```
however, we are expecting that the article is going to be a hash of params itself. When a string is passed we end up with this error.
Honeybadger: https://app.honeybadger.io/fault/66984/c7fc185e853bf779e3bfc58c6edd0208
```
TypeError: String does not have #dig method
articles_controller.rb  106 article_params(...)
[PROJECT_ROOT]/app/controllers/api/v0/articles_controller.rb:106:in `article_params'
104           :main_image, :canonical_url, :description, tags: []
105         ]
106         allowed_params << :organization_id if params.dig("article", "organization_id") && allowed_to_change_org_id?
107         params.require(:article).permit(allowed_params)
108       end
```

Solution: We should fail gracefully when this happens and return an unprocessable entity error with a helpful error message to the user. Make sure to include a couple of tests with your fix! 

Steps to Reproduce:
Make a request to the API Articles create endpoint with the params
```
{
  "article" => "body_markdown",
  "published" => "False",
  "description" => "test description",
  "format" => "json",
  "controller" => "api/v0/articles",
  "action" => "create"
}
```

### PR DESCRIPTION
**Pull request by atsmith813**
## What type of PR is this? (check all applicable)
- [x] Bug Fix

## Description
Fixes #5957. Unhelpful errors from the `articles_controller` were being raised if a user submitted the article param in the wrong format (not a Hash/JSON object).

This PR adds logic to check the format of the article param and specs to test the case where a user submits incorrectly formatted article params.

## Related Tickets & Documents
#5957

## Added to documentation?
- [x] no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

power_ranger_gif

### CODE REVIEW

File: app/controllers/api/v0/articles_controller.rb [hunk 1]
```diff
@@ -116,6 +118,13 @@ def allowed_to_change_org_id?
             @user.any_admin?
         end
       end
+
+      def validate_article_param_is_hash
+        return if params[:article].respond_to?(:dig)
```
Comment (citizen428) [inline app/controllers/api/v0/articles_controller.rb]: I know people aren't big on explicit type checking in Ruby, but `dig` is available arrays, structs, and even `CSV::Row`. If we need a hash, than the explicit `unless params[:article].is_a?(Hash)` seems like the better choice.

Comment (atsmith813) [reply app/controllers/api/v0/articles_controller.rb]: Great point - I usually go with non-explicit type checking, but this makes a lot of sense! Updated.

**Comment by citizen428** [comment]
Actually this broke all the specs, probably because it isn't actually a hash, but an instance of `ActionController::Parameters`.

**Comment by atsmith813** [comment]
@citizen428 actually, the specs fail because technically params are `ActionController::Parameters` and not a `Hash`.

**Comment by citizen428** [comment]
Haha, @atsmith813 we posted this pretty much at the same time. I guess `ActionController::Parameters` also implements `dig`, which is why this originally worked.

**Comment by atsmith813** [comment]
Updated per our conversation - specs are fixed!

**Comment by citizen428** [comment]
@rhymes For context, this was the result of a quick Slack pairing @atsmith813 and I did on the issue.

1. I suggested a more explicit check than `respond_to?(:dig)` since that method is available on many collections.
2. However, `is_a?(Hash)` doesn't work because `params` are instances of `ActionController::Parameters`
3. We discussed two approaches, the one you see here with `to_unsafe_h` or `params.require(article: [article_attributes])`. Since we're not using the result of this, the feeling was that we can live with `to_unsafe_h`.
